spring.application.name=servicio-etl

# CDM Metadata
omop.metadata.cdm.version=5.4
omop.metadata.vocabulary.version=5.0
omop.metadata.etl.version=1.0

# Legacy CDM Metadata
legacy.metadata.cdm.cdmSourceName=CDM_SOURCE_NAME
legacy.metadata.cdm.cdmSourceAbbreviation=CDM_SOURCE_TYPE
legacy.metadata.cdm.cdmHolder=CDM_HOLDER
legacy.metadata.cdm.cdmSourceDescription=CDM_SOURCE_DESCRIPTION
legacy.metadata.cdm.sourceDocumentationReference=CDM_SOURCE_DOCUMENTATION_REFERENCE
legacy.metadata.cdm.cdmEtlReference=CDM_ETL_REFERENCE
legacy.metadata.cdm.sourceReleaseDate=CDM_SOURCE_RELEASE_DATE
legacy.metadata.cdm.cdmVersion=CDM_VERSION
legacy.metadata.cdm.cdmVersionConceptId=CDM_VERSION_CONCEPT_ID
legacy.metadata.cdm.vocabularyVersion=VOCABULARY_VERSION