spring.application.name=servicio-etl

# CDM Metadata
omop.metadata.cdm.version=5.4
omop.metadata.vocabulary.version=5.0
omop.metadata.etl.version=1.0

# Legacy CDM Metadata
legacy.metadata.cdm.cdm-source-name=CDM_SOURCE_NAME
legacy.metadata.cdm.cdm-source-abbreviation=CDM_SOURCE_TYPE
legacy.metadata.cdm.cdm-holder=CDM_HOLDER
legacy.metadata.cdm.cdm-source-description=CDM_SOURCE_DESCRIPTION
legacy.metadata.cdm.source-documentation-reference=CDM_SOURCE_DOCUMENTATION_REFERENCE
legacy.metadata.cdm.cdm-etl-reference=CDM_ETL_REFERENCE
legacy.metadata.cdm.cdm-release-date=2026-06-04
legacy.metadata.cdm.source-release-date=2026-06-04
legacy.metadata.cdm.cdm-version=CDM_VERSION
legacy.metadata.cdm.cdm-version-conceptId=0
legacy.metadata.cdm.vocabulary-version=VOCABULARY_VERSION

# PostgreSQL
spring.datasource.url=jdbc:postgresql://db-omop:5432/omop_db?reWriteBatchedInserts=true
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Request configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB