server {
    listen 80;
    server_name localhost;
    client_max_body_size 60M;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://fhir-service:8080/; 
    }

    location /omop/ {
        proxy_pass http://etl-service:8080/; 
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}